output:
  format: tab
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - typecheck
    - unconvert
    - varcheck
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
