dist: trusty
sudo: false
language: go
services:
  - postgresql
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
env:
  - GO111MODULE=on
install:
  - make setup
  - make install
script:
  - make lint
  - make test
  - make enforce
  - make coveralls
