dist: trusty
os: linux
language: go
services:
  - postgresql
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
env:
  - GO111MODULE=on
install:
  - make setup
  - make install
script:
  - make lint
  - make test
  - make enforce
  - make coveralls
