dist: trusty
os: linux
language: go
services:
  - postgresql
go:
  - 1.21.x
  - 1.22.x
  - 1.23.x
install:
  - make setup
  - make install
script:
  - make lint
  - make test
  - make enforce
  - make coveralls
