name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  Build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: go_pg_migrations
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: go_pg_migrations_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
        check-latest: true

    - name: Set up
      run: make setup

    - name: Install
      run: make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Enforce
      run: make enforce

    - name: Coveralls
      run: make coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
